### ISSUE TITLE
Update Go and dependencies

### ISSUE THREAD

**Issue by jameshearttech** [jamiemccrindle/gitpathchanges#2]
We are working on building a CI pipeline with Argo Events and Argo Workflows in K8s. We use Bitbucket Cloud for our hosted Git. The Bitbucket webhook does not include changed paths like Github so we need a way to determine that. Your project is perfect for this!

I noticed it's Go 1.16. I forked your repository. I updated it to use Go 1.20. I update the dependencies. I added a Dockerfile I'm using to build an image to run in K8s. Do you have any interest in updating your repository? I can open a pull request if so, otherwise I'll just stick with my fork.

**Comment by jamiemccrindle** [comment]
Hey! Thanks for comment. Always nice to hear that my stuff is being used. I’d almost forgotten about this repo : )

I’d probably stick with your fork. Good luck!
